env: "local"
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "admin"
  dbname: "postgres1"
  sslmode: "disable"
nats:
  cluster_id: "test-cluster"
  client_id: "client-123"
  url: "js://localhost:4222"
http_server:
  address: "localhost:8080"
  timeout: 5s
  idle_timeout: 60s
